export const UNFAIR_CLAUSE_PATTERNS = [
  {
    id: 'arbitrary_termination',
    label: 'Arbitrary Termination',
    keywords: ['terminate without notice', 'evict immediately', 'vacate without'],
    severity: 'high',
    description: 'Owner can remove tenant without notice or cause',
  },
  {
    id: 'deposit_forfeiture',
    label: 'Deposit Forfeiture',
    keywords: ['forfeit deposit', 'no refund', 'deposit non-refundable'],
    severity: 'high',
    description: 'Deposit withheld without valid reason',
  },
  {
    id: 'unrestricted_entry',
    label: 'Unrestricted Entry',
    keywords: ['enter at any time', 'access without notice', 'inspect without warning'],
    severity: 'high',
    description: 'Owner can enter property without prior notice',
  },
  {
    id: 'maintenance_shift',
    label: 'Maintenance Shifted to Tenant',
    keywords: ['tenant responsible for all repairs', 'all maintenance by tenant', 'tenant shall bear all costs'],
    severity: 'medium',
    description: 'Major repair costs unlawfully shifted to tenant',
  },
  {
    id: 'rent_hike_unilateral',
    label: 'Unilateral Rent Increase',
    keywords: ['rent may be revised', 'owner may increase', 'at owner discretion'],
    severity: 'medium',
    description: 'Rent can be increased without tenant consent',
  },
  {
    id: 'lock_in_harsh',
    label: 'Harsh Lock-in Penalty',
    keywords: ['lock-in', 'lock in period', 'early exit penalty'],
    severity: 'medium',
    description: 'Excessive financial penalty for early exit',
  },
  {
    id: 'subletting_ban',
    label: 'Absolute Subletting Ban',
    keywords: ['no subletting', 'subletting prohibited', 'no sub-let'],
    severity: 'low',
    description: 'Blanket ban on subletting without owner consent',
  },
  {
    id: 'illegal_interest',
    label: 'Excessive Late Fee Interest',
    keywords: ['interest per day', '% per month', 'penalty per day'],
    severity: 'high',
    description: 'Interest/penalty rates exceeding legal limits',
  },
  {
    id: 'utilities_manipulation',
    label: 'Utility Charge Manipulation',
    keywords: ['utility charges at owner discretion', 'electricity as deemed', 'water charges extra'],
    severity: 'medium',
    description: 'Owner can arbitrarily set utility charges',
  },
  {
    id: 'notice_waiver',
    label: 'Notice Period Waiver',
    keywords: ['waive notice', 'no notice required', 'without prior intimation'],
    severity: 'high',
    description: 'Tenant waives statutory right to notice period',
  },
]
